Assignment 10 august 22
HassamAzam/React-Practice pull request #10
Opened 2024-09-02 05:27 UTC by HassamAzam

https://github.com/user-attachments/assets/a057e32f-789b-443f-84ad-f4a5297d09c2

2024-09-02 07:05 UTC, RanaWaqar7550 requested changes

2024-09-02 07:05 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/Components/ButtonComponent.js
> +}) => {
if we are simply returning the component then we can also use shorthand operator

```suggestion
}) => (
    <Button onClick={onClick} color={color} variant={variant} {...props}>
      {label}
    </Button>
  );
```

2024-09-02 07:05 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/Components/ButtonComponent.js
> +      {label}
what if we doon't pass any label, we should have add default parameters.

2024-09-02 07:05 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/Components/ButtonComponent.js
> +export default ButtonComponent;
for components like these, we should use `prop-types`.

2024-09-02 07:05 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/Components/InputField.js
> +const InputField = ({ label, placeholder, type = "text", ...props }) => {
add a line before that.

2024-09-02 07:05 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/Components/InputField.js
> +  return (
same shorthand and prop-types

2024-09-02 07:05 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/Store/authSlice.js
> +      state.userEmail = action.payload;
we shouldn't handle authentications in store, becuase when on page reload, the store get updated. use localstorage, sessionstorage

2024-09-02 07:05 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/Store/userArraySlice.js
> +      const index = state.value.findIndex((user) => user.email === email);
what if i updated the email field?

2024-09-02 07:05 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/App/App.css
> +}
EOF (end of file)

2024-09-02 07:05 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/App/App.css
> +.formContainer {
add an extra line before that selector and do it for the rest of the file as well.

2024-09-02 07:05 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/App/App.js
> +          <Route path="/dashboard" element={<Dashboard />} />
Make another custom component, called `<PrivateRoute component={Dashboard} />` if any component present in privateComponent then it should pass / fullfil the authentication layer and then land on Private component.

2024-09-02 07:05 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/Pages/Dashboard.js
> +  const userEmail = useSelector((state) => state.auth.userEmail);
try `reselect` library

2024-09-02 07:05 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/Pages/Dashboard.js
> +  const loggedInUser = userArray.find((user) => user.email === userEmail);
this data should direct come from selector and You have to comment that reason why?

2024-09-02 07:05 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/Pages/Dashboard.js
> +    navigate("/login");
that would work for now.
what if in future, we have to logout by destorying the session or we need to call a logout API, in that scenario, we will nagivate `/login` page and then come back to dasboard page, untill logout API response's return. 

Make these two statments sync with each other

2024-09-02 07:05 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/Pages/Dashboard.js
> +    return null;
why return null?

2024-09-02 07:05 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/Pages/Login.js
> +import { login } from "../../Store/authSlice";
we only use Pascal cases for components, not store.

2024-09-02 07:05 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/Pages/Login.js
> +    const user = userArray.find((user) => user.email === values.email);
should come from selector

2024-09-02 07:05 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/Pages/Login.js
> +      if (user.password === values.password) {
use `?` notation for check weather the object is null or undefined. e.g

```suggestion
      if (user?.password === values?.password) {
```

2024-09-02 07:05 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/Pages/Login.js
> +        setTimeout(() => {
why making UI block for 2 sec? what if i continously start pressing login button again and again?

2024-09-02 07:05 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/Pages/Login.js
> +  const navigate = useNavigate();
I don't think you are setting document title anywhere. Make a custom function to handle that.

2024-09-02 07:05 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/Pages/SignUp.js
> +  const checkIfUserExists = (email) => {
use shorthand return statement

2024-09-02 07:05 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/Pages/SignUp.js
> +        open={true}
In React, if we don't need to explicity pass `true` as props. we simply use `open` without any props.

```
 <Modal
        open
        onClose={handleClose}
        aria-labelledby="registration-form"
        aria-describedby="registration-form-description"
/>
```

2024-09-02 07:05 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/App/App.js
> +import SignUp from '../Pages/SignUp';
Please look out lazy loading concepts and add lazy loading too your components.

2024-09-02 14:15 UTC, HassamAzam commented on Assignment-10-August-22/userprofile/src/containers/Pages/Login.js
> +    const user = userArray.find((user) => user.email === values.email);
I used in the start of the functional component to get an Array. If I use a hook inside a handler function, it gives error that hooks are only called components or inside other custom hook.
Is there another approach to this?

2024-09-03 06:45 UTC, RanaWaqar7550 requested changes

2024-09-03 06:45 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/Components/ButtonComponent.js
> +  label:"Button Name"
```suggestion
label: "Button Name"
```

2024-09-03 06:45 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/Components/InputField.js
> +const InputField = ({ label, placeholder, type = "text", ...props }) => (
missing proptypes, as this is a common component.

2024-09-03 06:45 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/Pages/Dashboard.js
> +  console.log("Logged user", loggedInUser);
console?

2024-09-03 06:45 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/Pages/Dashboard.js
> +    console.log("inside  the update functions");
?

2024-09-03 06:45 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/Pages/Dashboard.js
> +      if (values.email!==loggedInUser.email  && checkExistence(userArray,values.email))
we need to use linter properly with our code. 
Add to your IDE or run linter command before commit.

2024-09-03 06:45 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/Pages/Dashboard.js
> +                    label=""
missing label field

2024-09-03 06:45 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/Pages/Login.js
> +    const user = userArray.find((user) => user.email === values.email);
create a utility function and returns user data by giving email.

2024-09-03 06:45 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/Pages/Login.js
> +      if (user?.password === values?.password) {
by adding this above user check can be removed.

2024-09-03 06:45 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/Pages/Title.js
> +export default setDocumentTitle;
EOF

2024-09-03 06:45 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/Pages/Title.js
> +
Remove Unnecessary lines

2024-09-03 06:45 UTC, RanaWaqar7550 commented on Assignment-10-August-22/userprofile/src/containers/Pages/Title.js
> +const setDocumentTitle = (title) => {
this is a utility function. create a utils folder under pages and move this file there and make file name with camelCase letter or small letters if its not a component.

2024-09-04 10:50 UTC, RanaWaqar7550 approved these changes

2024-09-04 10:50 UTC, merged